PipeLineTest/Controllers/PublishingController.cs
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace PipeLineTest.Controllers
{
    public class PublishingController : Controller
    {
        // GET: Publishing
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
                try
                {
                    string path = Path.Combine(Server.MapPath("~/Files"),
                       Path.GetFileName(file.FileName));
                    file.SaveAs(path);
                    return Json(new
                    {
                        Message = "File Uploaded Successfully!",
                        FilePath = file.FileName
                    }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception)
                {
                    return Json(new { Error = false, Message = "File Not Uploaded" }, JsonRequestBehavior.AllowGet);
                }

            ViewBag.Message = "You have not specified a file.";

            return View();
        }

        public FileResult ShowDocument(string filePath)
        {
            return File(Server.MapPath("~/Files/") + filePath, GetMimeType(filePath));
        }

        //Multipurpose Internet Mail Extensions(Mime) - used to describe content of various files
        private string GetMimeType(string fileName)
        {
            string mimeType = "application/unknown";
            string ext = Path.GetExtension(fileName).ToLower();

            Microsoft.Win32.RegistryKey regKey = Microsoft.Win32.Registry.ClassesRoot.OpenSubKey(ext);

            if (regKey != null && regKey.GetValue("Content Type") != null)
            {
                mimeType = regKey.GetValue("Content Type").ToString();
            }
            return mimeType;
        }

    }
}

PipeLineTest/Views/Shared/_Layout.cshtml
@using PipeLineTest.Controllers
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="../../Scripts/form.js" type="text/javascript"></script>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ADAL Publishing Pipeline</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type='text/javascript'>
        var appInsights = window.appInsights ||
            function (config) {
                function r(config) {
                    t[config] = function () {
                        var i = arguments;
                        t.queue.push(function () { t[config].apply(t, i) })
                    }
                }

                var t = { config: config }, u = document, e = window, o = 'script', s = u.createElement(o), i, f;
                for (s.src = config.url || '//az416426.vo.msecnd.net/scripts/a/ai.0.js', u.getElementsByTagName(o)[0]
                        .parentNode.appendChild(s), t.cookie = u
                        .cookie, t.queue = [], i = ['Event', 'Exception', 'Metric', 'PageView', 'Trace', 'Ajax'];
                    i.length;
                ) r('track' + i.pop());
                return r('setAuthenticatedUserContext'), r('clearAuthenticatedUserContext'),
                    config.disableExceptionTracking ||
                    (i = 'onerror', r('_' + i), f = e[i], e[i] = function (config, r, u, e, o) {
                        var s = f && f(config, r, u, e, o);
                        return s !== !0 && t['_' + i](config, r, u, e, o), s
                    }), t
            }({
                instrumentationKey: '5c3672b7-2034-4cba-a41e-f876f72377f6'
            });

        window.appInsights = appInsights;
        appInsights.trackPageView();

    </script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ADAL Pipeline Publishing", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("ADAL Publishing", "Index", "Publishing")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ADAL Publishing Pipeline</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>